version: "3"

services:
  frontend:
    build:
      context: ./lab-match-app-router
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: /rest
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - NEXT_PUBLIC_BASE_URL=/rest

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - /etc/letsencrypt/live/labsreputation.com/fullchain.pem:/etc/letsencrypt/live/labsreputation.com/fullchain.pem
        - /etc/letsencrypt/live/labsreputation.com/privkey.pem:/etc/letsencrypt/live/labsreputation.com/privkey.pem
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
  collect-author-data:
    build: 
      context: ./service/collect-pi-data
      dockerfile: Dockerfile

networks:
  app_network:
    driver: bridge
