version: "3"

services:
  frontend:
    build:
      context: ./lab-match
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: /rest
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - NEXT_PUBLIC_BASE_URL=/rest

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
